services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ecommerce-legado
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce_network_legado

  app:
    build: .
    container_name: ecommerce-api-legado
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce_db
      SPRING_DATASOURCE_USERNAME: ecommerce_user
      SPRING_DATASOURCE_PASSWORD: ecommerce_pass
    networks:
      - ecommerce_network_legado

volumes:
  mysql_data:

networks:
  ecommerce_network_legado:
    driver: bridge
